# Generated by Django 4.2.4 on 2023-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.CharField(max_length=11),
        ),
    ]
