# Generated by Django 4.2.4 on 2023-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0002_alter_reservas_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='cantidadClientes',
            field=models.CharField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='reservas',
            name='email',
            field=models.EmailField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='reservas',
            name='fechaReserva',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservas',
            name='horaReserva',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
