# Generated by Django 4.2.4 on 2023-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0003_reservas_cantidadclientes_reservas_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='horaReserva',
            field=models.TimeField(auto_now=True),
        ),
    ]
