# Generated by Django 4.2.4 on 2023-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0004_alter_reservas_horareserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='horaReserva',
            field=models.TimeField(),
        ),
    ]
