# Generated by Django 4.2.4 on 2023-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0006_alter_reservas_cantidadclientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='observacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
