# Generated by Django 4.2.4 on 2023-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_app', '0007_reservas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
